# 以下の形式で記述すること
# browser:
#   width: 起動するブラウザ(Chrome)の横幅
#   height: 起動するブラウザ(Chrome)の横幅
# timeout: アクセス時タイムアウト値(ms)
# log:
#   filepath: ログファイルパス
#   filename: ログファイル名

pages:
  filepath: config
  filename: pages.csv
browser:
  width: 1920
  height: 1080
  timeout: 60000
  headless_mode: False # Trueにするとアクセス時に403 Forbiddenとなってしまうので、実質False固定
log:
  filepath: log
  filename: ipo_manager.log
