site:
  login_url: https://www.fruitmail.net/login?go_html=https://www.fruitmail.net/game/
  game_top_url: https://www.fruitmail.net/game/
  campus_url: https://www.fruitmail.net/game/campus/
  bingo_url: https://www.fruitmail.net/bingo/index.php
  scratch_url: https://www.fruitmail.net/scratch/
  rank_gacha_url: https://www.fruitmail.net/rankgacha
  chirashi_url: https://www.fruitmail.net/chirashi/
  prize_everyday_url: https://www.fruitmail.net/prize/everyday/
  prize_point_url: https://www.fruitmail.net/prize/point/
  prize_gorgeous_url: https://www.fruitmail.net/prize/gorgeous/
  daily_ad_click_url: https://www.fruitmail.net/clickpoint/daily
  hidden_point_url: https://moni.fruitmail.net/hidden_point/?p-1/
  prize_present_slot_url: https://slot.fruitmail.net/present_slot/
  prize_roulette_url: https://www.fruitmail.net/prize/roulette/

browser:
  headless: False
  timeout: 15000 # これより小さいとログイン失敗する

bingo:
  max_click: 4

game:
  top: True
  bingo: True
  scratch: True
  chirashi: True
  rank_gacha: True
  prize_present_slot: True
  prize_roulette: True

campus:
  calculate:
    active: True
  arithmetic:
    active: True
  balance:
    active: True
  proverb:
    active: True
    max_combo_attempts: 3
    db:
      filepath: ./db/campus.db
  complex_kanji:
    active: True
    max_combo_attempts: 3
    db:
      filepath: ./db/campus.db
  sanji:
    active: True
    max_combo_attempts: 3
    db:
      filepath: ./db/campus.db
  medal:
    medal_off_marker: medal_icon_off.png
    active: False

routine:
  prize_everyday: True
  prize_point: True
  prize_gorgeous: True
  daily_ad_click: True
  hidden_point: True
