site:
  login_url: https://www.fruitmail.net/login?go_html=https://www.fruitmail.net/game/
  bingo_url: https://www.fruitmail.net/bingo/index.php
  scratch_url: https://www.fruitmail.net/scratch/
  prize_present_slot_url: https://slot.fruitmail.net/present_slot/

browser:
  headless: false
  timeout: 30000

bingo:
  max_click: 4