# 以下の形式で記述すること
# base_url: 株価取得先URL
# stocks:
#  - name: 上場企業名
#    country: ja or us(ja: 日本株、us: 米国株)
#    code: 企業コード
#    category: 企業の業種。現在未使用(備考代わり)
#  ...
# csv:
#  - filepath: 出力先ディレクトリ
#  - filename: 出力先CSVファイル名
#  - header: ヘッダ
# browser:
#   width: 起動するブラウザ(Chrome)の横幅
#   height: 起動するブラウザ(Chrome)の横幅
#   timeout: アクセス時タイムアウト値(ms)
#   headless_mode: ヘッドレスモードかどうか(基本どちらでも動作する)
# log:
#   filepath: ログファイルパス
#   filename: ログファイル名
base_url: https://finance.yahoo.co.jp/quote
stocks:
  - name: 企業名
    country: 国
    code: コード
    category: 未定
csv:
  filepath: dist
  filename: stocks.csv
  header:
    - 日時
    - 銘柄コード
    - 銘柄名
    - 株価(円)
browser:
  width: 1920
  height: 1080
  timeout: 60000
  headless_mode: True
log:
  filepath: log
  filename: stock_getter.log
